//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFunctions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/blackjack/", ConfigurationName="DatabaseFunctions.DatabaseSoap")]
    public interface DatabaseSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://localhost/blackjack/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/blackjack/SignUp", ReplyAction="*")]
        DatabaseFunctions.SignUpResponse SignUp(DatabaseFunctions.SignUpRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://localhost/blackjack/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/blackjack/Authenticate", ReplyAction="*")]
        DatabaseFunctions.AuthenticateResponse Authenticate(DatabaseFunctions.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://localhost/blackjack/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/blackjack/CurrencyAmount", ReplyAction="*")]
        DatabaseFunctions.CurrencyAmountResponse CurrencyAmount(DatabaseFunctions.CurrencyAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUp", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.SignUpRequestBody Body;
        
        public SignUpRequest() {
        }
        
        public SignUpRequest(DatabaseFunctions.SignUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class SignUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public SignUpRequestBody() {
        }
        
        public SignUpRequestBody(string userName, string key) {
            this.userName = userName;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignUpResponse", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.SignUpResponseBody Body;
        
        public SignUpResponse() {
        }
        
        public SignUpResponse(DatabaseFunctions.SignUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class SignUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignUpResult;
        
        public SignUpResponseBody() {
        }
        
        public SignUpResponseBody(bool SignUpResult) {
            this.SignUpResult = SignUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(DatabaseFunctions.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hash;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string userName, string hash) {
            this.userName = userName;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(DatabaseFunctions.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(int AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyAmount", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.CurrencyAmountRequestBody Body;
        
        public CurrencyAmountRequest() {
        }
        
        public CurrencyAmountRequest(DatabaseFunctions.CurrencyAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class CurrencyAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public CurrencyAmountRequestBody() {
        }
        
        public CurrencyAmountRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyAmountResponse", Namespace="http://localhost/blackjack/", Order=0)]
        public DatabaseFunctions.CurrencyAmountResponseBody Body;
        
        public CurrencyAmountResponse() {
        }
        
        public CurrencyAmountResponse(DatabaseFunctions.CurrencyAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/blackjack/")]
    public partial class CurrencyAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CurrencyAmountResult;
        
        public CurrencyAmountResponseBody() {
        }
        
        public CurrencyAmountResponseBody(double CurrencyAmountResult) {
            this.CurrencyAmountResult = CurrencyAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseSoapChannel : DatabaseFunctions.DatabaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseSoapClient : System.ServiceModel.ClientBase<DatabaseFunctions.DatabaseSoap>, DatabaseFunctions.DatabaseSoap {
        
        public DatabaseSoapClient() {
        }
        
        public DatabaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatabaseFunctions.SignUpResponse DatabaseFunctions.DatabaseSoap.SignUp(DatabaseFunctions.SignUpRequest request) {
            return base.Channel.SignUp(request);
        }
        
        public bool SignUp(string userName, string key) {
            DatabaseFunctions.SignUpRequest inValue = new DatabaseFunctions.SignUpRequest();
            inValue.Body = new DatabaseFunctions.SignUpRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.key = key;
            DatabaseFunctions.SignUpResponse retVal = ((DatabaseFunctions.DatabaseSoap)(this)).SignUp(inValue);
            return retVal.Body.SignUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatabaseFunctions.AuthenticateResponse DatabaseFunctions.DatabaseSoap.Authenticate(DatabaseFunctions.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public int Authenticate(string userName, string hash) {
            DatabaseFunctions.AuthenticateRequest inValue = new DatabaseFunctions.AuthenticateRequest();
            inValue.Body = new DatabaseFunctions.AuthenticateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.hash = hash;
            DatabaseFunctions.AuthenticateResponse retVal = ((DatabaseFunctions.DatabaseSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatabaseFunctions.CurrencyAmountResponse DatabaseFunctions.DatabaseSoap.CurrencyAmount(DatabaseFunctions.CurrencyAmountRequest request) {
            return base.Channel.CurrencyAmount(request);
        }
        
        public double CurrencyAmount(string userName) {
            DatabaseFunctions.CurrencyAmountRequest inValue = new DatabaseFunctions.CurrencyAmountRequest();
            inValue.Body = new DatabaseFunctions.CurrencyAmountRequestBody();
            inValue.Body.userName = userName;
            DatabaseFunctions.CurrencyAmountResponse retVal = ((DatabaseFunctions.DatabaseSoap)(this)).CurrencyAmount(inValue);
            return retVal.Body.CurrencyAmountResult;
        }
    }
}
